### ISSUE TITLE
Crashes in Bitwig when using multiple plugin instances

### ISSUE THREAD

**Issue by tas-from-planet-u-he** [free-audio/clap-wrapper#34]
Tested on macOS Monterey 12.6.1 with a 2020 M1 Silicon MacBook Pro using Bitwig 4.4.2.
Can not reproduce in Reaper.
Tested with u-he Hive 2.

Two methods to produce a crash reliably:

1)
* load one wrapped plugin instance (doesn't seem to matter which u-he plugin you use), close its GUI
* load a second wrapped plugin instance of that plugin
* unload that second wrapped instance (i.e. delete the track)
* open the GUI of the first instance, it shows up for a second, then crashes

2)
* load one plugin instance, keep its GUI open (important)
* load a second instance of that plugin
* unload that second instance (i.e. delete the track)
* load yet another instance of the plugin = crash

**Comment by defiantnerd** [comment]
this should be solved by latest commit to main.

**Comment by tas-from-planet-u-he** [comment]
Tried it after updating to the latest main branch.
Used Hive 2 with Bitwig 4.4.6 on M1 Mac.
Can still reproduce both ways to crash by following the guidelines.

**Comment by tas-from-planet-u-he** [comment]
Tried it again using Bitwig 5.1.2 on M1 Sonoma.
Could not reproduce those crashes anymore. Fixed.
